name: Master

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: elisa-normal

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        check-latest: true

    - uses: azure/setup-helm@v4

    - uses: helm/chart-testing-action@v2.6.1

    - name: Lint chart
      run: ct lint --chart-dirs keydb --charts keydb --validate-maintainers=false

    - name: Create kind cluster
      uses: helm/kind-action@v1

    - name: Install required CRDs
      run: kubectl apply -f keydb/test-crds/service-monitor.yaml

    - name: Install chart
      run: ct install --chart-dirs keydb --charts keydb --helm-extra-set-args "--set=topologySpreadConstraints="

    - name: Notify failure
      if: failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} [${{ github.event.ref }}](${{ github.event.repository.html_url }}/tree/${{ github.event.ref }}) build failed."
      run: |
        send-to-mattermost
