name: Master

on:
  release:
    types:
    - published

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        check-latest: true

    - uses: azure/setup-helm@v4
    - name: Package chart
      run: helm package ./keydb/ --destination ./.deploy/ --version ${{github.ref_name}}

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      with:
        skip_packaging: true
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_PACKAGE_PATH: .deploy
        CR_INDEX_PATH: index.yaml
        CR_SKIP_EXISTING: true
