name: Master

on:
  release:
    types:
      - published

env:
  CR_INDEX_PATH: "${{ github.workspace }}/.cr-index"
  CR_PACKAGE_PATH: "${{ github.workspace }}/.cr-release-packages"
  CR_TOOL_PATH: "${{ github.workspace }}/.cr-tool"

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          check-latest: true

      - name: Install Helm
        uses: azure/setup-helm@v4

      # - name: Install CR tool
      #   run: |
      #     mkdir "${CR_TOOL_PATH}"
      #     mkdir "${CR_PACKAGE_PATH}"
      #     mkdir "${CR_INDEX_PATH}"
      #     curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/v1.6.1/chart-releaser_1.6.1_linux_amd64.tar.gz"
      #     tar -xzf cr.tar.gz -C "${CR_TOOL_PATH}"
      #     rm -f cr.tar.gz

      # - name: Create helm package
      #   run: |
      #     "${CR_TOOL_PATH}/cr" package ./keydb/ --package-path "${CR_PACKAGE_PATH}"
      #     echo "Result of chart package:"
      #     ls -l "${CR_PACKAGE_PATH}"

      - name: Package chart
        run: helm package ./keydb/ --destination ./.deploy/ --version ${{github.ref_name}}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: keydb
          config: cr.yaml
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_PACKAGE_PATH: .deploy
          CR_INDEX_PATH: index.yaml
          CR_SKIP_EXISTING: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push charts to GHCR
        run: |
          shopt -s nullglob
          for pkg in .deploy/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/keydb-charts"
          done
