name: Master

on:
  release:
    types:
      - published
env:
  CR_OWNER: ${{ github.actor }}
  CR_GIT_REPO: ${{ github.event.repository.name }}
  CR_PACKAGE_PATH: .deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set username and email
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          check-latest: true

      - name: Install Helm
        uses: azure/setup-helm@v4

      - name: Package chart
        run: helm package ./keydb/ --destination ./${{env.CR_PACKAGE_PATH}} --version ${{github.ref_name}}

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@master
        with:
          charts_dir: keydb
          config: cr.yaml
          skip_packaging: true
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          # CR_PACKAGE_PATH: .deploy
          CR_INDEX_PATH: index.yaml
          CR_SKIP_EXISTING: true

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push charts to GHCR
        run: |
          shopt -s nullglob
          for pkg in .deploy/*.tgz; do
            if [ -z "${pkg:-}" ]; then
              break
            fi
            helm push "${pkg}" "oci://ghcr.io/${GITHUB_REPOSITORY_OWNER}/keydb-charts"
          done
