name: Release

on:
  release:
    types:
    - published

jobs:
  release-helm-chart:
    permissions:
      contents: write
    runs-on: elisa-normal

    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure Git
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@elisa.fi"

    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        check-latest: true

    - uses: azure/setup-helm@v4

    - name: Package chart
      run: helm package ./keydb/ --destination ./.deploy/ --version ${{github.ref_name}}

    - name: Run chart-releaser
      uses: helm/chart-releaser-action@v1.5.0
      with:
        skip_packaging: true
      env:
        CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        CR_PACKAGE_PATH: .deploy
        CR_INDEX_PATH: index.yaml
        CR_SKIP_EXISTING: true

    - name: Notify failure
      if: failure()
      env:
        MATTERMOST_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        MATTERMOST_TEXT: "${{ github.repository }} release [${{ github.event.release.tag_name }}](${{ github.event.release.html_url }}) build failed."
      run: |
        send-to-mattermost
